services:
  proxy:
    image: nginx
    restart: unless-stopped
    expose:
      - 80
    networks:
      - backend
      - virtual-hosts
    depends_on:
      - api
      - web
    labels:
      - traefik.http.routers.web-dnevik.rule=Host(`dnevnik.kewldan.ru`)
      - traefik.enable=true
      - traefik.http.services.web-dnevik.loadbalancer.server.port=80
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
  web:
    build: ./web
    restart: unless-stopped
    expose:
      - 80
    networks:
      - backend
  api:
    build: ./api
    restart: unless-stopped
    networks:
      - backend
    expose:
      - 80
    volumes:
      - ./data:/usr/app/data

networks:
  backend:
  virtual-hosts:
    external: true
